# Generated by Django 5.1.1 on 2024-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_persona_apellido_persona_correoelectronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fechadegrado',
            new_name='fechagrado',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='participacion',
            new_name='oferta',
        ),
        migrations.AlterField(
            model_name='persona',
            name='correoelectronico',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
