# Generated by Django 5.1.1 on 2024-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_fechadegrado_persona_fechagrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='oferta',
            field=models.CharField(max_length=500),
        ),
    ]
