# Generated by Django 5.1.1 on 2024-11-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_persona_correoelectronico_persona_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='correoelectronico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ubicacion_laboral',
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechagrado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='programa',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_laboral', models.CharField(max_length=100)),
                ('correoelectronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('oferta', models.CharField(max_length=200)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidades', to='login.persona')),
            ],
        ),
    ]
