# Generated by Django 5.1.1 on 2024-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_persona_correoelectronico_persona_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechagrado',
            field=models.DateField(default='01-01-2000'),
        ),
    ]
