# Generated by Django 5.1.1 on 2024-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_persona_fechagrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechagrado',
            field=models.DateField(default='16-06-2021'),
        ),
    ]
