# Generated by Django 5.1.1 on 2024-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_persona_correoelectronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('ano_grado', models.IntegerField()),
                ('cargo_actual', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('trayectoria', models.TextField()),
                ('datos_adicionales', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
