# Generated by Django 5.1.1 on 2024-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_egresado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='imagen_url',
            field=models.URLField(),
        ),
    ]
