# Generated by Django 5.1.1 on 2024-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_egresado_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='egresado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='egresados/'),
        ),
    ]
