# Generated by Django 5.1.1 on 2024-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_egresado_imagen_url_egresado_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes_principales/')),
            ],
        ),
    ]
