# Generated by Django 5.1.1 on 2024-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_egresado_imagen_egresado_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(upload_to='multimedia/')),
                ('imagen2', models.ImageField(upload_to='multimedia/')),
                ('imagen3', models.ImageField(upload_to='multimedia/')),
                ('imagen4', models.ImageField(upload_to='multimedia/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenPrincipal',
        ),
    ]
