# Generated by Django 5.1.1 on 2024-12-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_imagen_delete_imagenprincipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='imagen4',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='multimedia/'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='imagen1', max_length=100, unique=True),
        ),
    ]
