# Generated by Django 5.1.1 on 2024-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_remove_imagen_imagen1_remove_imagen_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
