# Generated by Django 5.1.1 on 2024-12-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_imagen_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
