# Generated by Django 5.1.1 on 2024-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_rename_nombre_imagen_nombres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='nombres',
        ),
        migrations.AddField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
