# Generated by Django 5.1.1 on 2024-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_imagen_nombres_imagen_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='egresado',
            name='Imagen_egre',
            field=models.ImageField(blank=True, default='egresado/default.jpg', upload_to='egresado/'),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='multimedia/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
