# Generated by Django 5.1.1 on 2024-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_remove_egresado_imagen_url_egresado_imagen_egre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='Imagen_egre',
        ),
        migrations.AddField(
            model_name='egresado',
            name='Imagen',
            field=models.ImageField(default='egresado/default.jpg', upload_to='egresado/'),
        ),
    ]
